import streamlit as st
from database import initialize_database, save_workflow_event, get_all_workflow_events
from services.quote_engine import calculate_quote_risk
from services.claims_engine import analyze_claim_text
from services.retrieval_engine import search_policy_documents
from tabs.quote_tab import render_quote_tab

initialize_database()

st.set_page_config(
    page_title="Insurance AI Copilot Suite",
    page_icon="🛡️",
    layout="wide"
)

st.markdown("""
<style>
.main {
    background-color: #0b1220;
}

h1, h2, h3 {
    color: white;
}

.stTabs [data-baseweb="tab-list"] {
    gap: 20px;
}

.stTabs [data-baseweb="tab"] {
    background-color: #111827;
    color: white;
    border-radius: 10px;
    padding: 10px 18px;
}

.stButton > button {
    background: linear-gradient(90deg, #2563eb, #1d4ed8);
    color: white;
    border: none;
    border-radius: 8px;
    padding: 10px 18px;
    font-weight: bold;
}

.stButton > button:hover {
    background: linear-gradient(90deg, #1d4ed8, #1e40af);
}

div[data-testid="stMetric"] {
    background-color: #111827;
    padding: 15px;
    border-radius: 10px;
}
</style>
""", unsafe_allow_html=True)

st.title("🛡️ Insurance AI Copilot Suite")
st.subheader("Enterprise GenAI Platform for Insurance Operations")

st.markdown("### Executive Performance Dashboard")
st.caption("Operational view of automation, human review load, confidence health, and platform reliability.")

top_col1, top_col2, top_col3, top_col4 = st.columns([1, 1, 1, 1])

records = get_all_workflow_events()

total_records = len(records)

if total_records == 0:
    automation_rate = 0
    review_queue = 0
    exception_rate = 0
    avg_latency = 0
else:
    automated_count = sum(1 for row in records if row[9] == "No")
    review_queue = sum(1 for row in records if row[9] == "Yes")
    completed_count = sum(1 for row in records if row[11] == "Completed")

    automation_rate = round((automated_count / total_records) * 100, 1)
    exception_rate = round(((total_records - completed_count) / total_records) * 100, 1)

    latency_values = [row[10] for row in records if row[10] is not None]

    avg_latency = round(sum(latency_values) / len(latency_values), 2) if latency_values else 0

top_col1.metric("Automation Rate", f"{automation_rate}%")
top_col2.metric("Human Review Queue", review_queue)
top_col3.metric("Exception Rate", f"{exception_rate}%")
top_col4.metric("Avg Latency", f"{avg_latency}s")
bottom_col1, bottom_col2, bottom_col3, bottom_col4 = st.columns([1, 1, 1, 1])

quote_count = sum(1 for row in records if row[1] == "Quote Intake")
claim_count = sum(1 for row in records if row[1] == "Claim Intake")

confidence_values = [row[7] for row in records if row[7] is not None]
avg_confidence = round(sum(confidence_values) / len(confidence_values), 1) if confidence_values else 0

platform_status = "Healthy" if total_records > 0 else "Idle"

quote_count = sum(1 for row in records if row[1] == "Quote Intake")
claim_count = sum(1 for row in records if row[1] == "Claim Intake")

confidence_values = [row[7] for row in records if row[7] is not None]
avg_confidence = round(sum(confidence_values) / len(confidence_values), 1) if confidence_values else 0

platform_status = "Healthy" if total_records > 0 else "Idle"

bottom_col1.metric("Quotes Automated", quote_count)
bottom_col2.metric("Claims Processed", claim_count)
bottom_col3.metric("Confidence Health", f"{avg_confidence}%")
bottom_col4.metric("Platform Status", platform_status)
st.info(
    "Dashboard V3: Metrics are calculated from SQLite workflow records generated by Quote and Claims workflows. "
    "This provides a local audit trail and operational reporting layer for the prototype."
)

st.markdown("### V3 Workflow Audit Records")

records = get_all_workflow_events()

if records:
    st.caption("Latest workflow activity stored in SQLite.")

    import pandas as pd

    table_data = []

    for row in records[:10]:
        table_data.append({
            "ID": row[0],
            "Type": row[1],
            "Request ID": row[2],
            "Time": row[3],
            "Module": row[4],
            "Risk": row[5],
            "Route": row[6],
            "Status": row[11],
        })

    df = pd.DataFrame(table_data)

    st.dataframe(df, width="stretch")
else:
    st.caption("No workflow records yet.")

tab1, tab2, tab3, tab4 = st.tabs([
    "Quote Copilot",
    "Policy Retrieval",
    "Claims Copilot",
    "AI Orchestrator"
])

with tab1:
    from datetime import datetime
    import uuid
    import re

    st.header("Quote Copilot")
    st.caption("AI-assisted quote intake with validation, privacy protection, audit metadata, risk scoring, and routing explanation.")

    st.warning(
        "V2 Note: This is simulated enterprise logic for prototype/demo purposes. "
        "In a real system, SSN should be avoided unless legally required, encrypted, tokenized, and never stored in plain text."
    )

    us_states_and_territories = [
        "Select State / Territory",
        "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
        "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
        "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
        "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
        "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
        "DC", "PR", "GU", "VI", "AS", "MP"
    ]

    col1, col2 = st.columns(2)

    with col1:
        name = st.text_input("Customer Name *")
        email = st.text_input("Email *")
        phone = st.text_input("Phone *")
        ssn = st.text_input("SSN *", placeholder="Example: 123-45-6789")
        age = st.number_input("Age *", min_value=16, max_value=100, value=30)

    with col2:
        state = st.selectbox("State / Territory *", us_states_and_territories)
        zip_code = st.text_input("ZIP Code *", placeholder="Example: 60601")
        vehicle = st.selectbox("Vehicle Type *", ["Sedan", "SUV", "Truck", "EV", "Sports Car", "Luxury SUV"])
        accidents = st.number_input("Accidents in Last 3 Years", min_value=0, max_value=10, value=0)
        prior_claims = st.number_input("Prior Claims", min_value=0, max_value=10, value=0)

    def is_valid_name(value):
        cleaned = value.strip()

        if len(cleaned) < 2:
            return False

        if cleaned.isdigit():
            return False

        return bool(re.match(r"^[A-Za-z\s\-']+$", cleaned))

    def is_valid_email(value):
        cleaned = value.strip()
        return bool(re.match(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$", cleaned))

    def is_valid_phone(value):
        digits_only = "".join(char for char in value if char.isdigit())
        return len(digits_only) == 10

    def is_valid_ssn(value):
        digits_only = "".join(char for char in value if char.isdigit())

        if len(digits_only) != 9:
            return False

        if digits_only.startswith("000"):
            return False

        if digits_only[3:5] == "00":
            return False

        if digits_only[5:] == "0000":
            return False

        return True

    def is_valid_zip_code(value):
        digits_only = "".join(char for char in value if char.isdigit())
        return len(digits_only) == 5

    def mask_name(value):
        parts = value.strip().split()
        masked_parts = []

        for part in parts:
            first_letter = part[0].upper()
            masked_parts.append(first_letter + "***")

        return " ".join(masked_parts)

    def mask_email(value):
        username, domain = value.split("@", 1)

        if len(username) <= 2:
            return username[0] + "***@" + domain

        return username[:2] + "***@" + domain

    def mask_phone(value):
        digits_only = "".join(char for char in value if char.isdigit())
        return "***-***-" + digits_only[-4:]

    def mask_ssn(value):
        digits_only = "".join(char for char in value if char.isdigit())
        return "***-**-" + digits_only[-4:]

    def mask_zip(value):
        digits_only = "".join(char for char in value if char.isdigit())
        return digits_only[:2] + "***"

    if st.button("Generate Quote Summary"):
        errors = []

        if not is_valid_name(name):
            errors.append("Customer Name must be at least 2 letters and cannot contain numbers or special symbols.")

        if not is_valid_email(email):
            errors.append("Email must be valid, like customer@example.com.")

        if not is_valid_phone(phone):
            errors.append("Phone must contain exactly 10 digits, like 5551234567 or (555) 123-4567.")

        if not is_valid_ssn(ssn):
            errors.append("SSN must contain exactly 9 digits and cannot use invalid groups like 000, 00, or 0000.")

        if state == "Select State / Territory":
            errors.append("State / Territory is required.")

        if not is_valid_zip_code(zip_code):
            errors.append("ZIP Code must contain exactly 5 digits.")

        if errors:
            st.error("Quote intake cannot continue. Please fix the required fields below.")
            for error in errors:
                st.write(f"- {error}")

        else:
            quote_result = calculate_quote_risk(
                age=age,
                accidents=accidents,
                prior_claims=prior_claims,
                vehicle_type=vehicle
            )

            risk_score = quote_result["risk_score"]
            raw_score = quote_result["raw_score"]
            risk_level = quote_result["risk_level"]
            route = quote_result["route"]
            human_review_required = quote_result["human_review_required"]

            base_score = quote_result["base_score"]
            accidents_score = quote_result["accidents_score"]
            claims_score = quote_result["claims_score"]
            age_score = quote_result["age_score"]
            vehicle_score = quote_result["vehicle_score"]

            risk_reasons = []

            if accidents > 0:
                risk_reasons.append("Prior accident history")

            if prior_claims > 0:
                risk_reasons.append("Prior claims frequency")

            if age < 25:
                risk_reasons.append("Young driver segment")

            if vehicle in ["Truck", "EV", "Sports Car", "Luxury SUV"]:
                risk_reasons.append("Higher-cost vehicle class")

            if risk_level == "High":
                compliance_status = "Needs Manual Review"
                override_allowed = "No"
                routing_explanation = "High risk score triggered senior underwriting review."
            elif risk_level == "Medium":
                compliance_status = "Compliant"
                override_allowed = "Yes"
                routing_explanation = "Moderate risk profile sent to standard underwriting."
            else:
                compliance_status = "Compliant"
                override_allowed = "Yes"
                routing_explanation = "Low risk profile eligible for straight-through processing."

            request_id = "QUOTE-" + str(uuid.uuid4())[:8].upper()
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            save_workflow_event(
                event_type="Quote Intake",
                request_id=request_id,
                module_name="Quote Copilot",
                risk_level=risk_level,
                route=route,
                confidence=100 - risk_score,
                escalation_flag="Yes" if human_review_required == "Yes" else "No",
                human_review_required=human_review_required,
                latency_seconds=1.2,
                status="Completed",
                notes=f"Quote processed for {state} {vehicle}. Risk score: {risk_score}/100."
            )

            st.success("Quote intake completed with validation, privacy-safe processing, and audit tracking.")

            metric1, metric2, metric3, metric4 = st.columns(4)
            metric1.metric("Risk Score", f"{risk_score}/100")
            metric2.metric("Risk Level", risk_level)
            metric3.metric("Routing Decision", route)
            metric4.metric("Human Review Required", human_review_required)

            if raw_score > 100:
                st.info(f"Raw score was {raw_score}, but the displayed enterprise risk score is capped at 100/100 for readability.")

            st.subheader("Risk Scoring Breakdown")
            st.write(f"Base Score: {base_score}")
            st.write(f"Accidents Score: {accidents_score}")
            st.write(f"Prior Claims Score: {claims_score}")
            st.write(f"Age Score: {age_score}")
            st.write(f"Vehicle Score: {vehicle_score}")
            st.write(f"Final Risk Score: {risk_score}/100")

            st.subheader("Routing Explanation")
            st.info(routing_explanation)

            st.subheader("Top Risk Reasons")

            if risk_reasons:
                for reason in risk_reasons:
                    st.write(f"- {reason}")
            else:
                st.write("- No major risk signals detected")

            st.subheader("Compliance Decision")
            st.write(f"Compliance Status: {compliance_status}")
            st.write(f"Manual Override Allowed: {override_allowed}")

            st.subheader("Privacy-Safe Customer Summary")
            st.write(f"Customer: {mask_name(name)}")
            st.write(f"Email: {mask_email(email)}")
            st.text(f"Phone: {mask_phone(phone)}")
            st.text(f"SSN: {mask_ssn(ssn)}")
            st.write(f"Age: {age}")
            st.write(f"State / Territory: {state}")
            st.write(f"ZIP Code: {mask_zip(zip_code)}")
            st.write(f"Vehicle: {vehicle}")
            st.write(f"Accidents: {accidents}")
            st.write(f"Prior Claims: {prior_claims}")

            st.subheader("Audit Metadata")
            st.write(f"Request ID: {request_id}")
            st.write(f"Timestamp: {timestamp}")
            st.write("Rules Version: quote-risk-rules-v3.0")
            st.write("Model/Provider Version: services.quote_engine")
            st.write(f"Human Review Required: {human_review_required}")

            st.info("AI Recommendation: Continue quote workflow using validated customer data, masked PII, visible scoring logic, and auditable routing metadata.")

with tab2:
    import uuid

    st.header("Policy Retrieval Engine")
    st.caption("Simulated RAG-style policy search with query-aware retrieval, source snippets, confidence scoring, and low-confidence warnings.")

    st.warning("V2 Note: This is simulated local retrieval for prototype/demo purposes. It is not connected to a real vector database yet.")

    question = st.text_input(
        "Ask a policy question *",
        placeholder="Example: Is collision damage covered after a rear-end accident?"
    )

    policy_documents = [
        {
            "title": "Auto Policy Section 4.2 — Collision Coverage",
            "keywords": ["collision", "accident", "crash", "rear-end", "vehicle damage", "damage"],
            "snippet": "Collision coverage may apply when an insured vehicle is damaged due to impact with another vehicle or object, subject to deductible and active policy status.",
            "answer": "Collision damage may be covered if the customer carries collision coverage. Final payout depends on deductible, exclusions, and whether the policy was active at the time of loss."
        },
        {
            "title": "Claims Handbook Section 2.1 — Deductibles",
            "keywords": ["deductible", "payment", "payout", "claim payment", "out of pocket"],
            "snippet": "The deductible is the customer responsibility amount subtracted from an approved claim payment before final payout is issued.",
            "answer": "The deductible is the amount the customer must pay before the insurer issues the final approved claim payout."
        },
        {
            "title": "State Rules Addendum — Texas Vehicle Rules",
            "keywords": ["texas", "tx", "state rule", "state rules", "vehicle rules"],
            "snippet": "Texas vehicle claims may require state-specific review depending on coverage type, liability details, and claim documentation.",
            "answer": "Texas vehicle claims may require state-specific review before final claim handling or payout decisions."
        },
        {
            "title": "Rental Reimbursement Section 5.3",
            "keywords": ["rental", "rental car", "replacement car", "temporary vehicle"],
            "snippet": "Rental reimbursement may apply when the policy includes rental coverage and the covered vehicle is unavailable due to a covered loss.",
            "answer": "Rental reimbursement may be available if the customer purchased rental coverage and the vehicle is unavailable because of a covered claim."
        },
        {
            "title": "Comprehensive Coverage Section 3.7",
            "keywords": ["fire", "theft", "hail", "flood", "vandalism", "comprehensive"],
            "snippet": "Comprehensive coverage may apply to non-collision losses such as theft, fire, hail, flood, vandalism, or falling objects.",
            "answer": "Comprehensive coverage may apply to non-collision losses such as fire, theft, hail, flood, or vandalism, depending on policy terms."
        }
    ]

    def calculate_match_score(user_question, document):
        question_lower = user_question.lower()
        matched_keywords = []

        for keyword in document["keywords"]:
            if keyword in question_lower:
                matched_keywords.append(keyword)

        score = len(matched_keywords) * 25

        if score > 95:
            score = 95

        return score, matched_keywords

    if st.button("Search Policy Knowledge Base"):
        errors = []

        if not question.strip():
            errors.append("Policy question is required.")

        if errors:
            st.error("Policy retrieval cannot continue. Please fix the required field below.")
            for error in errors:
                st.write(f"- {error}")

        else:
            retrieval_results = search_policy_documents(question)

            st.subheader("Top Retrieved Matches")

            if retrieval_results:
                for index, result in enumerate(retrieval_results[:3], start=1):
                    st.write(f"{index}. {result['title']}")
                    st.progress(result["score"])
                    st.write(f"Source Snippet: {result['snippet']}")
                    st.write(f"Matched Keywords: {', '.join(result['matched_keywords'])}")
                    st.markdown("---")

                top_result = retrieval_results[0]
                confidence = top_result["score"]
                sources_used = min(len(retrieval_results), 3)
                request_id = "RET-" + str(uuid.uuid4())[:8].upper()

                save_workflow_event(
                    event_type="Policy Retrieval",
                    request_id=request_id,
                    module_name="Policy Retrieval",
                    risk_level="N/A",
                    route="Knowledge Response",
                    confidence=confidence,
                    escalation_flag="Yes" if confidence < 70 else "No",
                    human_review_required="Yes" if confidence < 70 else "No",
                    latency_seconds=0.9,
                    status="Completed",
                    notes=f"Policy search: {question[:60]}"
                )

                st.subheader("Grounded AI Answer")

                if confidence >= 70:
                    st.success(top_result["answer"])
                elif confidence >= 40:
                    st.warning(top_result["answer"])
                    st.info("Moderate confidence: human review recommended before using this answer with a customer.")
                else:
                    st.warning("Low confidence: the system found limited matching policy content. Human review is required before answering.")

                col1, col2, col3 = st.columns(3)
                col1.metric("Confidence", f"{confidence}%")
                col2.metric("Sources Used", sources_used)
                col3.metric("Retrieval Mode", "Keyword RAG Sim")

                st.info("Response generated only from retrieved simulated internal policy content.")

            else:
                request_id = "RET-" + str(uuid.uuid4())[:8].upper()

                save_workflow_event(
                    event_type="Policy Retrieval",
                    request_id=request_id,
                    module_name="Policy Retrieval",
                    risk_level="N/A",
                    route="Human Review Required",
                    confidence=0,
                    escalation_flag="Yes",
                    human_review_required="Yes",
                    latency_seconds=0.9,
                    status="Completed",
                    notes=f"No strong policy match found for: {question[:60]}"
                )

                st.warning("Low confidence: no strong policy match found for this question.")
                st.write("Try asking about collision, deductible, Texas rules, rental coverage, fire, theft, hail, flood, or vandalism.")

                col1, col2, col3 = st.columns(3)
                col1.metric("Confidence", "0%")
                col2.metric("Sources Used", "0")
                col3.metric("Retrieval Mode", "Keyword RAG Sim")

                st.error("Human review required because no grounded source was retrieved.")

with tab3:
    from datetime import datetime
    import uuid

    st.header("Claims Intake Copilot")
    st.caption("AI-assisted claim triage with urgency detection, escalation flags, dynamic missing-info checks, and human handoff.")

    st.warning("V2 Note: This is simulated claims triage logic for prototype/demo purposes. It is not a real claim approval or fraud model.")

    claim_text = st.text_area(
        "Paste claim notes *",
        height=180,
        placeholder="Example: Rear-end accident in Dallas. Minor bumper damage. No injuries."
    )

    if st.button("Analyze Claim"):
        errors = []

        if not claim_text.strip():
            errors.append("Claim notes are required.")

        if errors:
            st.error("Claim analysis cannot continue. Please fix the required field below.")
            for error in errors:
                st.write(f"- {error}")

        else:
            claim_id = "CLAIM-" + str(uuid.uuid4())[:8].upper()
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            claim_result = analyze_claim_text(claim_text)

            urgency = claim_result["urgency"]
            detected_urgency_signals = claim_result["detected_urgency_signals"]
            escalation_flags = claim_result["escalation_flags"]
            missing_items = claim_result["missing_items"]
            recommended_route = claim_result["recommended_route"]
            human_review_required = claim_result["human_review_required"]

            save_workflow_event(
                event_type="Claim Intake",
                request_id=claim_id,
                module_name="Claims Copilot",
                risk_level=urgency,
                route=recommended_route,
                confidence=85 if urgency == "Low" else 70 if urgency == "Medium" else 55,
                escalation_flag="Yes" if escalation_flags else "No",
                human_review_required=human_review_required,
                latency_seconds=1.6,
                status="Completed",
                notes=f"Claim analyzed with {len(escalation_flags)} escalation flags and {len(missing_items)} missing items."
            )

            st.success("Claim analysis completed with validation, signal detection, and routing logic.")

            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Urgency", urgency)
            col2.metric("Missing Items", len(missing_items))
            col3.metric("Escalation Flags", len(escalation_flags))
            col4.metric("Human Review Required", human_review_required)

            st.subheader("Detected Urgency Signals")

            if detected_urgency_signals:
                for signal in detected_urgency_signals:
                    st.write(f"- {signal}")
            else:
                st.write("- No specific urgency keywords detected")

            st.subheader("Escalation Flags")

            if escalation_flags:
                for flag in escalation_flags:
                    st.write(f"- {flag}")
            else:
                st.write("- No escalation flags detected")

            st.subheader("Dynamic Missing Information Checklist")

            if missing_items:
                for item in missing_items:
                    st.checkbox(item)
            else:
                st.success("No major missing information detected from the claim notes.")

            st.subheader("AI Claim Summary")
            st.write(
                f"The submitted claim was classified as {urgency} urgency. "
                f"The system detected {len(detected_urgency_signals)} urgency signal(s), "
                f"{len(escalation_flags)} escalation flag(s), and {len(missing_items)} missing item(s)."
            )

            st.subheader("Human Handoff Summary")
            st.info(
                f"Route to {recommended_route} with {urgency} priority. "
                f"Human review required: {human_review_required}. "
                "Request any missing documents before final claim decision."
            )

            st.subheader("Claim Audit Metadata")
            st.write(f"Claim ID: {claim_id}")
            st.write(f"Timestamp: {timestamp}")
            st.write("Rules Version: claims-triage-rules-v3.0")
            st.write("Model/Provider Version: services.claims_engine")
            st.write(f"Recommended Route: {recommended_route}")

with tab4:
    from datetime import datetime
    import uuid
    import random

    st.header("AI Workflow Orchestrator")
    st.caption("Simulated multi-agent enterprise workflow engine with statuses, timing, gates, escalation paths, and audit trail.")

    st.warning("V2 Note: This is simulated orchestration logic for prototype/demo purposes. It is not connected to real agents or MCP servers yet.")

    workflow_type = st.selectbox(
        "Select Incoming Workflow",
        [
            "Quote Request",
            "Policy Question",
            "Claim Intake"
        ]
    )

    if st.button("Run Workflow"):

        request_id = "WF-" + str(uuid.uuid4())[:8].upper()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if workflow_type == "Quote Request":
            final_state = "Completed"
            escalation = "No"
            route = "Quote Copilot Queue"

        elif workflow_type == "Policy Question":
            final_state = "Completed with Review"
            escalation = "Yes"
            route = "Policy Support Analyst"

        else:
            final_state = "Escalated"
            escalation = "Yes"
            route = "Senior Claims Adjuster"

        agents = [
            {
                "name": "Customer Request Agent",
                "purpose": "Receives inbound workflow request",
                "status": "Passed",
                "time": round(random.uniform(0.1, 0.4), 2),
                "gate": "Valid Input"
            },
            {
                "name": "Privacy Guard Agent",
                "purpose": "Masks PII before downstream processing",
                "status": "Passed",
                "time": round(random.uniform(0.1, 0.3), 2),
                "gate": "PII Protected"
            },
            {
                "name": "Retrieval Agent",
                "purpose": "Finds policy / claims knowledge",
                "status": "Passed",
                "time": round(random.uniform(0.2, 0.6), 2),
                "gate": "Sources Retrieved"
            },
            {
                "name": "Rules Engine Agent",
                "purpose": "Applies business logic and controls",
                "status": "Passed",
                "time": round(random.uniform(0.2, 0.5), 2),
                "gate": "Rules Applied"
            },
            {
                "name": "Risk Decision Agent",
                "purpose": "Calculates urgency / risk routing",
                "status": "Review" if escalation == "Yes" else "Passed",
                "time": round(random.uniform(0.2, 0.5), 2),
                "gate": "Decision Ready"
            },
            {
                "name": "Summary Agent",
                "purpose": "Creates human-readable summary",
                "status": "Passed",
                "time": round(random.uniform(0.1, 0.3), 2),
                "gate": "Summary Generated"
            },
            {
                "name": "Human Operations Agent",
                "purpose": "Receives escalated work when needed",
                "status": "Active" if escalation == "Yes" else "Standby",
                "time": round(random.uniform(0.1, 0.2), 2),
                "gate": "Handoff Ready"
            }
        ]

        total_time = round(sum(agent["time"] for agent in agents), 2)

        st.success("Workflow executed successfully.")

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Workflow Type", workflow_type)
        col2.metric("Agents Run", len(agents))
        col3.metric("Total Time", f"{total_time}s")
        col4.metric("Escalated", escalation)

        st.subheader("Live Agent Pipeline")

        for step_number, agent in enumerate(agents, start=1):
            st.info(
                f"Step {step_number}: **{agent['name']}** | "
                f"Status: {agent['status']} | "
                f"Time: {agent['time']}s | "
                f"Gate: {agent['gate']} \n\n"
                f"{agent['purpose']}"
            )

        st.subheader("Final Workflow Decision")
        st.write(f"Final State: {final_state}")
        st.write(f"Routed To: {route}")

        if escalation == "Yes":
            st.warning("Human review was required in this workflow.")
        else:
            st.success("Workflow completed without human escalation.")

        st.subheader("Workflow Audit Metadata")
        st.write(f"Request ID: {request_id}")
        st.write(f"Timestamp: {timestamp}")
        st.write("Orchestrator Version: workflow-engine-v2.0")
        st.write("Agent Runtime: simulated-local-agent-mesh")
        st.write(f"Workflow Type: {workflow_type}")

        st.subheader("Current System Metrics")

        col1, col2, col3 = st.columns(3)
        col1.metric("Agents Active", "7")
        col2.metric("Avg Response Time", f"{total_time}s")
        col3.metric("Escalation Rate", "8%")

        st.success("Platform Status: Healthy")